# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: true
julia:
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.5
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: doctest
          using ClassicAlgorithmsCollections
          doctest(ClassicAlgorithmsCollections)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - stage: "Coverage Test"
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
