name = "ClassicAlgorithmsCollections"
uuid = "200e722e-036e-465c-9f8f-9a25f0f9a217"
keywords = "alogrithms, graph-algorithms, linked-list, dynamic-programming, tree-structure, binary-search-tree, number-theory,  bit, bit-manipulation, string-manipulation, sorting-algorithms"
license = "MIT"
authors = ["Anselm Hahn <Anselm.Hahn@gmail.com>"]
description = "Coming soon"
repository = "https://github.com/Anselmoo/ClassicAlgorithmsCollections"
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
julia = ">= 1.5"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test"]
